name: Build ZN-M2 OpenWrt

on:
  workflow_dispatch:  # 手动触发编译
    inputs:
      target:
        description: '编译目标'
        required: true
        default: 'zn-m2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk flex git

      - name: Configure Device Tree
        run: |
          mkdir -p targets/ipq60xx/configs
          echo "CONFIG_TARGET_ipq60xx=y" >> targets/ipq60xx/configs/zn-m2_defconfig
          echo "CONFIG_TARGET_ipq60xx_generic=y" >> targets/ipq60xx/configs/zn-m2_defconfig
          echo "CONFIG_PACKAGE_kmod-qca-nss-drv=y" >> targets/ipq60xx/configs/zn-m2_defconfig

      - name: Compile Firmware
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make -j$(nproc) V=s
