name: Build ZN-M2 OpenWrt

on:
  workflow_dispatch:
    inputs:
      target:
        description: '编译目标'
        required: true
        default: 'zn-m2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk flex git device-tree-compiler

      - name: Configure Device Tree
        run: |
          # 自动复制设备树文件（已通过网页上传）
          echo "设备树文件已通过网页上传至 targets/ipq60xx/dts/zn-m2.dts"

      - name: Update Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate .config
        run: |
          make defconfig

      - name: Compile Firmware
        run: |
          make -j$(nproc) V=s
