name: Build OpenWrt
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 增加手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取你的仓库代码（包含dts文件）
        uses: actions/checkout@v4

      - name: 调试1：查看当前仓库根目录的文件结构
        run: |
          echo "当前工作目录: $(pwd)"
          echo "根目录文件列表："
          ls -la
          echo "dts 文件夹内容："
          ls -la dts || echo "dts文件夹不存在"  # 增加错误处理

      - name: 克隆 OpenWrt 源码
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          path: openwrt
          fetch-depth: 1  # 浅克隆加速

      - name: 调试2：确认 OpenWrt 源码的克隆路径
        run: |
          echo "OpenWrt 源码目录："
          ls -la openwrt

      - name: 复制 DTS 文件
        run: |
          # 确保目标目录存在
          mkdir -p openwrt/target/linux/ipq60xx/dts
          # 复制DTS文件并验证
          if [ -f "dts/zn-m2.dts" ]; then
            cp dts/zn-m2.dts openwrt/target/linux/ipq60xx/dts/
            echo "DTS文件复制成功"
            ls -la openwrt/target/linux/ipq60xx/dts/zn-m2.dts
          else
            echo "错误：dts/zn-m2.dts文件不存在"
            exit 1
          fi

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk flex git gettext libssl-dev \
            xsltproc wget curl unzip python3

      - name: 加载配置文件
        run: |
          cd openwrt
          # 检查配置文件是否存在
          if [ -f "../configs/zn-m2_defconfig" ]; then
            cp ../configs/zn-m2_defconfig .config
            make defconfig
          else
            echo "错误：../configs/zn-m2_defconfig文件不存在"
            exit 1
          fi

      - name: 编译固件
        run: |
          cd openwrt
          make download -j$(nproc)
          # 首次失败时重试单线程编译以获取详细日志
          make -j$(nproc) || make -j1 V=s

      - name: 检查构建输出
        run: |
          echo "构建输出目录结构："
          ls -R openwrt/bin/targets/ipq60xx/ || echo "构建目录不存在"
          echo "生成的固件文件："
          find openwrt/bin/targets/ipq60xx/ -type f || echo "未找到固件文件"

      - name: 上传编译好的固件
        uses: actions/upload-artifact@v4
        with:
          name: zn-m2-firmware
          path: |
            openwrt/bin/targets/ipq60xx/**/*
            # 同时上传DTS文件作为参考
            openwrt/target/linux/ipq60xx/dts/zn-m2.dts
          retention-days: 30
          if-no-files-found: error  # 无文件时视为错误
