name: Build ZN-M2 OpenWrt

on:
  workflow_dispatch:  # 手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码和你的自定义文件
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt  # 拉取官方OpenWrt源码
          ref: main  # 可替换为你需要的版本（如23.05）
          path: openwrt  # 源码存到openwrt目录

      - name: 自动复制你的DTS文件到正确位置
        run: |
          # 假设你的DTS在仓库根目录的dts/zn-m2.dts，复制到OpenWrt的DTS目录
          # 注意：ipq60xx是ZN-M2的平台，根据实际平台修改路径
          mkdir -p openwrt/target/linux/ipq60xx/dts
          cp openwrt/dts/zn-m2.dts openwrt/target/linux/ipq60xx/dts/

      - name: 自动安装依赖（无需手动输入）
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk flex git gettext libssl-dev \
            xsltproc wget curl unzip python3

      - name: 自动配置编译参数（关键：避免命令行交互）
        run: |
          cd openwrt
          # 复制你的专用配置文件到OpenWrt根目录
          cp ../configs/zn-m2_defconfig .config
          # 自动生成完整配置（无需手动运行menuconfig）
          make defconfig

      - name: 自动编译固件
        run: |
          cd openwrt
          # 自动下载依赖并编译（-j$(nproc)自动利用所有CPU核心）
          make download -j$(nproc)
          make -j$(nproc) V=s  # V=s显示详细编译日志，方便排查错误

      - name: 自动上传编译好的固件
        uses: actions/upload-artifact@v4
        with:
          name: zn-m2-firmware  # 固件包名称
          # 编译好的固件路径（根据实际平台修改ipq60xx）
          path: openwrt/bin/targets/ipq60xx/*/*
          retention-days: 30  # 固件保留30天
