name: Build OpenWrt for IPQ60xx (zn-m2)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取本地代码（含配置和DTS）
        uses: actions/checkout@v4

      - name: 调试1：查看本地文件结构
        run: |
          echo "当前目录: $(pwd)"
          ls -la
          ls -la configs || echo "configs文件夹不存在"
          ls -la dts || echo "dts文件夹不存在"

      - name: 克隆支持ipq60xx的专用源码（robimarko仓库）
        uses: actions/checkout@v4
        with:
          repository: robimarko/openwrt  # 明确支持ipq60xx的仓库
          path: openwrt
          fetch-depth: 0
          ref: ipq60xx  # 专用分支，确保ipq60xx支持

      - name: 验证源码是否支持ipq60xx
        run: |
          echo "检查ipq60xx架构目录是否存在："
          if [ -d "openwrt/target/linux/ipq60xx" ]; then
            echo "✅ 源码支持ipq60xx架构"
            ls -la openwrt/target/linux/ipq60xx  # 显示目录内容确认
          else
            echo "❌ 源码不支持ipq60xx，请更换为robimarko/openwrt等专用仓库"
            exit 1
          fi

      - name: 安装编译依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk flex git gettext libssl-dev \
            xsltproc wget curl unzip python3 python3-setuptools \
            libelf-dev rsync subversion gcc-multilib g++-multilib

      - name: 更新源码Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 复制设备树（DTS）文件
        run: |
          mkdir -p openwrt/target/linux/ipq60xx/dts
          if [ -f "dts/zn-m2.dts" ]; then
            cp dts/zn-m2.dts openwrt/target/linux/ipq60xx/dts/
            echo "DTS文件已复制："
            ls -la openwrt/target/linux/ipq60xx/dts/zn-m2.dts
          else
            echo "❌ 未找到dts/zn-m2.dts"
            exit 1
          fi

      - name: 加载并验证配置文件
        run: |
          cd openwrt
          if [ -f "../configs/zn-m2_defconfig" ]; then
            cp ../configs/zn-m2_defconfig .config
            make defconfig
          else
            echo "❌ 未找到configs/zn-m2_defconfig"
            exit 1
          fi

          if ! grep -q "TARGET_ipq60xx=y" .config; then
            echo "❌ 配置文件未生效，当前目标架构："
            grep "TARGET_" .config | grep "=y"
            exit 1
          else
            echo "✅ 已确认目标架构为ipq60xx"
          fi

      - name: 下载依赖包
        run: |
          cd openwrt
          make download -j$(nproc)
          if [ -z "$(ls -A dl/)" ]; then
            echo "❌ 依赖包下载失败"
            exit 1
          fi

      - name: 编译固件
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s  # 失败时单线程输出详细日志

      - name: 检查固件输出
        run: |
          echo "ipq60xx固件目录内容："
          ls -R openwrt/bin/targets/ipq60xx/ || echo "❌ 固件生成失败"
          echo "生成的固件文件："
          find openwrt/bin/targets/ipq60xx/ -type f -name "*.bin" -o -name "*.img"

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: zn-m2-ipq60xx-firmware
          path: openwrt/bin/targets/ipq60xx/**/*
          retention-days: 30
