name: Build ZN-M2 Firmware

on:
  push:
    branches: [ main ]
    paths:
      - 'target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6018-zn-m2.dts'
      - 'target/linux/qualcommax/image/ipq60xx.mk'
      - '.github/workflows/build-zn-m2-only.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 180

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
          submodules: 'recursive'

      - name: 系统环境准备
        run: |
          free -h
          df -h
          sudo fallocate -l 12G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: 配置依赖（增强libaudit搜索）
        run: |
          # 重置feeds配置
          echo "src-git packages https://git.openwrt.org/feed/packages.git" > feeds.conf.default
          echo "src-git luci https://git.openwrt.org/project/luci.git" >> feeds.conf.default
          echo "src-git routing https://git.openwrt.org/feed/routing.git" >> feeds.conf.default
          
          ./scripts/feeds clean
          ./scripts/feeds update -f -a
          
          # 仅删除冲突包
          rm -rf package/utils/audit
          
          # 克隆完整的packages源（增加深度确保完整）
          if [ ! -d "package/feeds/packages" ]; then
            git clone --depth=10 https://git.openwrt.org/feed/packages.git package/feeds/packages || {
              echo "错误：克隆packages源失败"
              exit 1
            }
          fi
          
          # 关键修复：全局搜索libaudit包（不局限于libs目录）
          echo "===== 搜索libaudit源 ====="
          LIBAUDIT_SOURCE=$(find package/feeds/packages -name "libaudit" -type d | head -n 1)
          
          if [ -z "$LIBAUDIT_SOURCE" ]; then
            echo "错误：未找到libaudit源"
            echo "===== 列出packages源中可能的相关目录 ====="
            ls -lh package/feeds/packages/libs/ | grep -i audit
            ls -lh package/feeds/packages/utils/ | grep -i audit
            ls -lh package/feeds/packages/security/ | grep -i audit  # 新增可能的安全目录
            exit 1
          fi
          
          # 提取libaudit
          if [ ! -d "package/libs/libaudit" ]; then
            mv "$LIBAUDIT_SOURCE" package/libs/
            echo "成功提取libaudit（来源：$LIBAUDIT_SOURCE）"
          fi
          
          # 搜索audit/host（解决build dependency）
          echo "===== 搜索audit/host源 ====="
          AUDIT_HOST_SOURCE=$(find package/feeds/packages -name "audit" -type d | head -n 1)
          
          if [ -z "$AUDIT_HOST_SOURCE" ]; then
            echo "错误：未找到audit/host源"
            ls -lh package/feeds/packages/utils/ | grep -i audit
            exit 1
          fi
          
          # 提取audit/host
          if [ ! -d "package/utils/audit" ]; then
            mv "$AUDIT_HOST_SOURCE" package/utils/
            echo "成功提取audit/host（来源：$AUDIT_HOST_SOURCE）"
          fi
          
          # 搜索libpci
          LIBPCI_SOURCE=$(find package/feeds/packages -name "libpci" -type d | head -n 1)
          if [ -z "$LIBPCI_SOURCE" ]; then
            echo "错误：未找到libpci源"
            ls -lh package/feeds/packages/libs/ | grep -i pci
            exit 1
          fi
          [ ! -d "package/libs/libpci" ] && mv "$LIBPCI_SOURCE" package/libs/ && echo "成功提取libpci"
          
          # 搜索policycoreutils
          POLICY_SOURCE=$(find package/feeds/packages -name "policycoreutils" -type d | head -n 1)
          if [ -z "$POLICY_SOURCE" ]; then
            echo "错误：未找到policycoreutils源"
            ls -lh package/feeds/packages/utils/ | grep -i policy
            exit 1
          fi
          [ ! -d "package/utils/policycoreutils" ] && mv "$POLICY_SOURCE" package/utils/ && echo "成功提取policycoreutils"
          
          # 提取其他依赖
          for lib in libev libpam libtirpc xz; do
            src=$(find package/feeds/packages -name "$lib" -type d | head -n 1)
            if [ -z "$src" ]; then
              echo "错误：未找到$lib源"
              exit 1
            fi
            [ ! -d "package/libs/$lib" ] && mv "$src" package/libs/ && echo "成功提取$lib"
          done
          
          # 提取net-snmp
          NET_SNMP_SOURCE=$(find package/feeds/packages -name "net-snmp" -type d | head -n 1)
          if [ -z "$NET_SNMP_SOURCE" ]; then
            echo "错误：未找到net-snmp源"
            exit 1
          fi
          [ ! -d "package/libs/net-snmp" ] && mv "$NET_SNMP_SOURCE" package/libs/ && echo "成功提取net-snmp"
          
          # 清理临时文件
          rm -rf package/feeds/packages
          
          # 强制安装依赖
          ./scripts/feeds install -a
          ./scripts/feeds install -p packages libaudit audit libpci policycoreutils net-snmp
          ./scripts/feeds install -p packages -f libaudit audit libpci policycoreutils
          
          # 验证依赖
          required_pkgs=(
            "package/libs/libaudit"
            "package/utils/audit"
            "package/libs/libpci"
            "package/utils/policycoreutils"
            "package/libs/net-snmp"
          )
          for pkg in "${required_pkgs[@]}"; do
            if [ ! -d "$pkg" ]; then
              echo "错误：依赖包 $pkg 仍缺失"
              exit 1
            fi
          done

      - name: 修复设备树
        run: |
          DTSI_FILE="target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6000-cmiot.dtsi"
          [ -f "$DTSI_FILE" ] && sed -i 's/#include "ipq6018-nss.dtsi"/\/\/&/' "$DTSI_FILE"

      - name: 生成配置
        run: |
          make distclean
          cat > .config <<EOF
          CONFIG_TARGET_qualcommax=y
          CONFIG_TARGET_qualcommax_ipq60xx=y
          CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_zn_zn-m2=y
          CONFIG_PACKAGE_ath11k-firmware-ipq6018=y
          CONFIG_PACKAGE_busybox=y
          CONFIG_PACKAGE_libaudit=y
          CONFIG_PACKAGE_audit=y
          CONFIG_PACKAGE_libpci=y
          CONFIG_PACKAGE_policycoreutils=y
          CONFIG_PACKAGE_net-snmp=y
          CONFIG_PACKAGE_libev=y
          CONFIG_PACKAGE_libpam=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_xz=y
          CONFIG_PACKAGE_audit_HOST=y
          CONFIG_PACKAGE_policycoreutils_HOST=y
          EOF
          make defconfig

      - name: 编译工具链
        run: |
          make -j1 toolchain/compile V=s 2> toolchain-errors.log
          if [ -s toolchain-errors.log ]; then
            echo "工具链编译错误："
            cat toolchain-errors.log
            exit 1
          fi

      - name: 验证工具链
        run: |
          TOOLCHAIN_DIR=$(find staging_dir/ -maxdepth 1 -type d -name "toolchain-aarch64_cortex-a53_*_musl" | head -n 1)
          [ -z "$TOOLCHAIN_DIR" ] && { echo "工具链目录缺失"; exit 1; }
          TOOLCHAIN_BIN="$TOOLCHAIN_DIR/bin"
          [ -f "$TOOLCHAIN_BIN/aarch64-openwrt-linux-musl-gcc" ] || { echo "编译器缺失"; exit 1; }
          $TOOLCHAIN_BIN/aarch64-openwrt-linux-musl-gcc --version || exit 1

      - name: 编译固件
        run: |
          make -j2 V=s 2> firmware-errors.log
          if [ -s firmware-errors.log ]; then
            echo "固件编译错误："
            cat firmware-errors.log
            exit 1
          fi

      - name: 检查产物
        run: |
          FIRMWARE_DIR="bin/targets/qualcommax/ipq60xx"
          ls $FIRMWARE_DIR/*zn_zn-m2*.bin || { echo "固件缺失"; exit 1; }

      - name: 上传固件
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zn-m2-${{ github.run_id }}
          files: bin/targets/qualcommax/ipq60xx/*zn_zn-m2*.bin

      - name: 上传错误日志
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            toolchain-errors.log
            firmware-errors.log
          retention-days: 14
