name: Build ZN-M2 Firmware

on:
  push:
    branches: [ main ]
    paths:
      - 'target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6018-zn-m2.dts'
      - 'target/linux/qualcommax/image/ipq60xx.mk'
      - '.github/workflows/build-zn-m2-only.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
          submodules: 'recursive'

      - name: 清理系统空间并安装核心依赖
        run: |
          # 清理系统垃圾
          sudo apt autoremove -y
          sudo apt clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          
          # 安装基础编译工具和32位库
          sudo apt update -y
          sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget \
            libelf-dev libtool-bin autoconf automake squashfs-tools m4 ncurses-term \
            lib32z1 lib32stdc++6 libc6-i386
          
          # 显示磁盘空间和已安装的关键库版本
          df -h
          dpkg -l | grep -E "gcc|g\+\+|lib32z1|libstdc\+\+"

      - name: 配置feeds并处理依赖
        run: |
          # 确保只使用官方源
          echo "src-git packages https://git.openwrt.org/feed/packages.git" > feeds.conf.default
          echo "src-git luci https://git.openwrt.org/project/luci.git" >> feeds.conf.default
          echo "src-git routing https://git.openwrt.org/feed/routing.git" >> feeds.conf.default
          echo "src-git telephony https://git.openwrt.org/feed/telephony.git" >> feeds.conf.default
          
          # 清理并更新feeds
          ./scripts/feeds clean
          ./scripts/feeds update -f -a
          
          # 安装必要的基础包及缺失的依赖库
          ./scripts/feeds install -a
          # 手动安装缺失的依赖（解决WARNING中提到的依赖问题）
          ./scripts/feeds install libev libpam libtirpc liblzma libnetsnmp
          
          # 卸载可能冲突的包
          ./scripts/feeds uninstall domoticz i2pd kea libtorrent-rasterbar

      - name: 修复设备树依赖
        run: |
          DTSI_FILE="target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6000-cmiot.dtsi"
          if [ -f "$DTSI_FILE" ]; then
            sed -i 's/#include "ipq6018-nss.dtsi"/\/\/#include "ipq6018-nss.dtsi"/g' "$DTSI_FILE"
            grep -n "ipq6018-nss.dtsi" "$DTSI_FILE"
          else
            echo "错误：未找到ipq6000-cmiot.dtsi"
            exit 1
          fi

      - name: 彻底清理并生成配置（修复.config语法错误）
        run: |
          export TERM=dumb
          make distclean
          
          # 生成默认配置
          make defconfig IGNORE_ERRORS=1
          
          # 确保.config格式正确（使用echo追加时避免语法错误）
          # 启用无线固件包
          echo "CONFIG_PACKAGE_ath11k-firmware-ipq6018=y" >> .config
          # 禁用第三方插件（严格使用"is not set"语法）
          echo "CONFIG_PACKAGE_chinadns-ng is not set" >> .config
          echo "CONFIG_PACKAGE_sing-box is not set" >> .config
          echo "CONFIG_PACKAGE_luci-theme-argon is not set" >> .config
          
          # 重新生成配置以自动修复语法错误
          make defconfig
          
          # 验证配置文件是否存在且无语法错误
          if [ ! -f ".config" ]; then
            echo "错误：.config文件生成失败"
            exit 1
          fi
          # 检查配置文件中的语法错误（查找可能的缺失分隔符）
          if grep -n -E '^[^#]+:[^=]+$' .config; then
            echo "错误：.config文件存在语法错误（缺失分隔符）"
            exit 1
          fi
          # 验证关键配置项
          cat .config | grep -E "ath11k-firmware-ipq6018|chinadns-ng|sing-box"

      - name: 编译交叉工具链（单线程模式）
        run: |
          export TERM=dumb
          rm -rf staging_dir/toolchain-aarch64_cortex-a53_musl
          make toolchain/clean V=s
          make -j1 toolchain/compile V=s 2>&1 | tee toolchain-build.log
          
          if grep -q "error:" toolchain-build.log; then
            echo "工具链编译错误："
            cat toolchain-build.log | grep -B 10 -A 10 "error:"
            exit 1
          fi

      - name: 验证交叉编译器
        run: |
          TOOLCHAIN_BIN="staging_dir/toolchain-aarch64_cortex-a53_musl/bin"
          if [ ! -d "$TOOLCHAIN_BIN" ]; then
            echo "工具链目录不存在：$TOOLCHAIN_BIN"
            exit 1
          fi
          if [ ! -f "$TOOLCHAIN_BIN/aarch64-openwrt-linux-musl-gcc" ]; then
            echo "交叉编译器未生成：$TOOLCHAIN_BIN/aarch64-openwrt-linux-musl-gcc"
            exit 1
          fi
          $TOOLCHAIN_BIN/aarch64-openwrt-linux-musl-gcc --version || {
            echo "交叉编译器无法运行"
            exit 1
          }

      - name: 编译固件
        run: |
          export TERM=dumb
          make -j2 V=s 2>&1 | tee full-build.log

      - name: 检查编译产物
        run: |
          FIRMWARE_DIR="bin/targets/qualcommax/ipq60xx"
          echo "固件目录内容："
          ls -lh $FIRMWARE_DIR
          
          if ! ls $FIRMWARE_DIR/*zn_zn-m2*.bin >/dev/null 2>&1; then
            echo "未找到ZN-M2固件文件"
            exit 1
          fi

      - name: 整理并上传固件
        if: success()
        run: |
          mkdir -p output
          cp -v $FIRMWARE_DIR/*zn_zn-m2*.bin output/
          cp -v $FIRMWARE_DIR/*zn_zn-m2*.img output/ || true

      - name: 创建发布
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zn-m2-${{ github.run_id }}
          files: output/*

      - name: 上传调试日志（失败时）
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: |
            toolchain-build.log
            full-build.log
            .config
            feeds.conf.default
          retention-days: 14
